version: "3.0"
services:
  database:
    # we're using 5.7 because there were connection issues with 8.0
    image: mysql:5.7
    volumes:
      - type: bind
        source: ./seed_data
        target: /docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
    ports:
      - target: 3306
        published: ${DATABASE_PORT:-3306}
        protocol: tcp
        mode: host
